README.md

Docs: README.md update

---

src/auth.py
src/playground/main.py
src/playground/saveFile.py
src/speech/STT.py
src/speech/convert.py
src/speech/main.py
src/tuning/convert.py

Feat: STT training data creation

---

src/playground/saveFile.py
src/tuning/convert.py

Feat: JSONL convert function in chat

---

key/model.json
src/_non-module/junhofile.ipynb
src/playground/client.py
src/playground/main_chat.py
src/playground/saveFile.py
src/tuning_STT/error.py

Feat: Chat model application with random emergency

---

src/playground/main_stt.py
src/train_llama/Makefile
src/tuning_STT/expand.py
src/tuning_STT/test_COT.py

Docs: Makefile update for colab

---

backend/functions/addUser.js

user data add function

---

backend/functions/gpt.js
backend/functions/index.js

1. gpt api 연동
2. 파이어베이스 연동 파일 추가

feat: gpt api

---

backend/functions/stt.js

feat: Google STT API intergration

---

backend/functions/server.js
backend/functions/stt.js

1. 녹음이 안 되는 문제 해결
2. 하나의 녹음 파일에 STT 전사가 2번 수행되던 문제 해결

bugfix: remove empty responses and duplicate responses

---

backend/functions/gpt.js
backend/functions/server.js
backend/functions/stt.js

1. 우물 정 누르면 대화 녹음
2. 대화 맥락을 반영해서 대화 진행

feat: WuMul Jung

---

backend/functions/callUser.js
backend/functions/gpt.js
backend/functions/server.js
backend/functions/stt.js

전화 종료시 유저와 관련된 데이터를 삭제해 이후에 다시 통화를 진행했을 때 대화 흐름에 영향이 없도록 수정

feat: Delete user data when call ends

---

backend/callUser.js
backend/gpt.js
backend/server.js
backend/stt.js
backend/tts.js

1.  FireStore에서 사용자 정보를 가져오던 작업을 DynamoDB에서 가져오도록 수정 
2. WebSocket 구현
3. STT 작업을 기존의 서버에서 음성 파일을 가져오는 방식에서 스트리밍 방식으로 수정
4. TTS 작업 추가

feat: WebSocket intergration

---

src/playground/main_chat.py
src/speech/baleum.py

Docs: Model update

---

src/common/auth_.py
src/common/documents.py
src/playground/main_chat.py
src/playground/saveFile.py
src/speech/baleum.py
src/speech/draw.py
src/speech/evaluate.py
src/tuning_STT/calculate.py
src/tuning_STT/convert.py

STT 결과 계산 기능
JSON파일 학습/검증 데이터 분리 기능
인증과정에서 키 파일 버전체크 기능 추가

Feat: Minor updates

---

backend/server.js
backend/stt.js
backend/tts.js

1. 사용자 응답 처리 시 스트림을 멈추고 사용자 응답 처리가 완료되면 스트림 초기화 후 재시작
2. STT 모듈 분리

feat: stream initialize and restart, separate STT module

---

backend/chatModel.js
backend/chatSummaryModel.js
backend/server.js
backend/sttCorrectionModel.js
backend/tts.js

1. 전화 종료시 사용자 데이터 초기화
2. TTS 동안 사용자 음성 차단

feat: Wipe data when phone ends and User voice is not processed during TTS

---

frontend/src/App.css
frontend/src/App.js

feat: Change speech bubble CSS

---

frontend/src/App.css

Design changes: Update speech bubble CSS

---

backend/server.js
backend/sttCorrectionModel.js
backend/tts.js

STT 교정 모델이 대화 맥락을 반영해서 STT 결과를 교정

feat: STT 교정 모델이 대화 맥락을 반영하도록 수정

---

backend/callUser.js
backend/server.js
frontend/src/App.css
frontend/src/App.js

1. DynamoDB에서 전화번호를 가져와 위기 유형 자동 설정하기
2. 드롭다운 리스트에서 선택한 위기 유형으로 DB 업데이트 및 전화 걸기
3. 웹 UI 수정

feat: DB와 연동하여 웹 페이지에서 전화걸기 

---

backend/package-lock.json
backend/package.json
backend/sttCorrectionModel.js
frontend/src/App.css
frontend/src/App.js

1. 대화 내용이 길어질 시 자동 스크롤 기능 추가
2. 의존성 패키지 업데이트

feat: 대화 내용이 길어질 시 자동 스크롤 기능 추가, other: 의존성 패키지 업데이트

---

backend/callUser.js
backend/chatModel.js
backend/chatSummaryModel.js
backend/server.js
backend/sttCorrectionModel.js
frontend/src/App.js

경쟁 문제 해결 중(현재는 임시방편으로 Map으로 해결했지만 추후 Redis와 같은 in-memory DB로 전환 필요)

feat: resolve Race Problem1

---

backend/callUser.js
backend/chatModel.js
backend/chatSummaryModel.js
backend/package-lock.json
backend/package.json
backend/playBeepSound.js
backend/server.js
backend/spreadsheet.js
backend/sttCorrectionModel.js
frontend/package-lock.json
frontend/package.json
frontend/src/App.js

1. 구글 스프레드시트에 모델별 대화 내용 저장
2. 의존성 패키지 업데이트
- [] No

feat: 구글 스프레드시트에 모델별 대화 내용 저장

---

.gitignore
backend/chatModel.js
backend/chatSummaryModel.js
backend/configLoader.js
backend/openaiClient.js
backend/playBeepSound.js
backend/server.js
backend/sttCorrectionModel.js
backend/tts.js

Code style update: GPT API 관련 공통 기능 모듈화

---

frontend/src/App.css

- [] Other... Please describe:
테스트

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트2

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트4

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트5

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트6

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트7

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트8

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트9

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작  테스트10

---

key/model.json
src/speech/validation/makedata.py

Feat: STT validation model renewal

---

frontend/src/App.css
frontend/src/App.js

말풍선에서 문장이 단어 단위로 줄 바꿈 되어 출력되도록 설정

Design change: 말풍선에서 문장이 단어 단위로 줄 바꿈 되어 출력되도록 설정

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트11

---

frontend/src/App.css

test: 자동으로 변경 사항 업데이트 및 서버 재시작 테스트12

---

key/model.json

test: 자동으로 변경 사항 업데이트 및 서버 재시작  테스트13

---

frontend/src/App.css

Design chage: 말풍선 최소 길이 지정

---

backend/server.js

test: jenkins 빌드 과정 시각화 test

---

key/model.json

Docs: STT model update

---

backend/server.js

test: 빌드 완료시 라벨링 추가

---

backend/server.js

test: 빌드 완료시 라벨링 추가2

---

key/model.json

chat model updated and now 2 models are available: 4o and 4o mini

---

src/playground/main_chat.py

EXPERIMENT CODE UPDATED
